const hints = {
  kinh: "Sinh sống chủ yếu ở đồng bằng và đô thị với hạ tầng hiện đại. Tuy nhiên, giới trẻ đang dần lãng quên các loại hình nghệ thuật và trang phục truyền thống.",
  tay: "Sống ở thung lũng Đông Bắc, canh tác lúa nước cực giỏi, con em học hành đỗ đạt cao. Dù vậy, những nếp nhà sàn đang bị thay bằng nhà xây, hát Then vắng bóng dần.",
  thai: "Nổi tiếng với múa Xòe và áo cóm vùng Tây Bắc. Du lịch giúp đời sống khá lên, nhưng phụ nữ ở các bản xa vẫn sinh con tại nhà do trạm y tế cách nhiều ngọn đồi.",
  muong: "Đời sống kinh tế ổn định nhờ giao thoa tốt với miền xuôi. Tuy nhiên, thanh niên hiện nay ít người còn biết đánh cồng chiêng hay nói trôi chảy tiếng mẹ đẻ.",
  khmer: "Sở hữu những ngôi chùa lộng lẫy ở đồng bằng sông Cửu Long. Đáng tiếc, hạn mặn khiến ruộng đồng thất thu, nhiều thanh niên phải bỏ học lên phố làm công nhân.",
  hoa: "Họ là những thương nhân tài ba ở các thành phố lớn. Con cái được tiếp cận y tế, giáo dục hàng đầu. Đổi lại, các bang hội cổ và tiếng nói riêng bị đồng hóa rất mạnh.",
  ede: "Nhờ trồng cà phê, cao su, kinh tế và y tế có khởi sắc rõ rệt. Đáng buồn thay, rừng cạn kiệt khiến những ngôi nhà dài không còn gỗ cất, chế độ mẫu hệ mờ nhạt dần.",
  "ba-na": "Sở hữu ngôi nhà Rông vút cao giữa đại ngàn. Các bản làng vẫn giữ truyền thống, nhưng đường xa cách trở khiến học sinh thiếu lớp học kiên cố.",
  "gia-rai": "Văn hóa nhà mồ và cồng chiêng Tây Nguyên rực rỡ. Dù vậy, đất canh tác bạc màu, đầu ra nông sản kém khiến cái nghèo vẫn đeo bám nhiều bản làng.",
  mong: "Sống trên đỉnh núi mây mù, giữ gìn hoàn hảo tục bắt vợ và dệt lanh. Đổi lại, kinh tế nương rẫy bấp bênh, trẻ em thiếu áo ấm và phải đi bộ rất xa để học chữ.",
  dao: "Giữ được chữ Nôm Dao và lễ cấp sắc uy nghi. Vì sống phân tán ở những nơi heo hút, đường đi lại sạt lở khiến việc khám chữa bệnh gặp vô vàn trở ngại.",
  "san-chay": "Sống tập trung ở trung du Bắc Bộ, ruộng nương khá phát triển. Dù no ấm, điệu múa xúc tép hay hát Sấng Cọ hiếm khi còn được vang lên trong làng.",
  "kho-mu": "Bậc thầy đan lát mây tre vùng Tây Bắc. Thường sống trên sườn núi rất dốc, bà con thiếu trầm trọng nước sạch sinh hoạt và trường học kiên cố cho con em.",
  chut: "Từng sống trong hang đá nguyên thủy, nay mới ra định cư ở biên giới Quảng Bình. Gặp muôn vàn khó khăn về thiếu đất sản xuất, y tế và giáo dục yếu kém.",
  tho: "Giao thoa mạnh mẽ với người Kinh ở Nghệ An, đời sống vật chất không ngừng cải thiện. Cái giá phải trả là ngôn ngữ và phong tục riêng gần như lụi tàn.",
  cham: "Di sản tháp gạch và chữ viết đồ sộ. Trường học xây kiên cố nhưng các làng nghề dệt, gốm đang điêu đứng vì ế ẩm, lớp trẻ không mặn mà nối nghiệp.",
  "co-ho": "Cư trú ở Nam Tây Nguyên, giữ được nghề dệt thổ cẩm bằng khung cửi cổ. Đang rất cần được hỗ trợ vốn và đường sá để đưa nông sản ra thị trường.",
  "xo-dang": "Sinh sống quanh núi Ngọc Linh, văn hóa phong phú. Kinh tế phụ thuộc vào rẫy, cần hỗ trợ thêm về kỹ thuật nông nghiệp hiện đại và tủ thuốc y tế bản.",
  "san-diu": "Rất thạo làm ruộng nước và chăn nuôi, đời sống khá giả. Nhưng điệu hát Soọng Cô tuyệt hay nay chỉ còn những bậc cao niên thỉnh thoảng nhớ lại.",
  hre: "Bảo tồn điệu hát Ka-choi và cồng chiêng độc đáo ở miền núi Quảng Ngãi. Địa hình đồi núi dốc khiến kinh tế tự cung tự cấp còn muôn vàn vất vả.",
  "ra-glai": "Chủ nhân của những bộ đàn đá thiêng liêng sườn Đông Trường Sơn. Tỷ lệ suy dinh dưỡng trẻ em còn khá do phụ thuộc nương rẫy nứt nẻ mùa khô.",
  nung: "Giỏi làm mộc và đan lát ở vùng núi phía Bắc. Đời sống no ấm, nhưng vải chàm nhuộm tay xưa kia nay đã hoàn toàn nhường chỗ cho quần áo may sẵn.",
  "la-chi": "Giữ gìn tục cúng hoàng cung và tết Khu Cù Tê rất đặc biệt. Do sống ở sườn dốc cheo leo, thiếu đất canh tác lúa nước, tỷ lệ học sinh đến trường còn thấp.",
  "phu-la": "Nổi tiếng với những bộ váy áo trang trí bằng hạt cườm công phu. Địa hình đồi núi dốc cản trở việc buôn bán, sinh kế phụ thuộc nương rẫy bấp bênh.",
  "la-hu": "Từng mệnh danh là tộc 'Lá vàng' xưa, nay đã được dựng bản định cư. Xuất phát điểm quá thấp khiến họ thiếu thốn toàn diện cả y tế, trường lớp và thức ăn.",
  "la-ha": "Có tiếng nói riêng rất cổ, cư trú tại vùng sâu Sơn La. Đời sống còn nhiều khó khăn bủa vây, thiếu trầm trọng nước sinh hoạt sạch và lớp học cho trẻ.",
  "ha-nhi": "Chủ nhân của những thửa ruộng bậc thang kỳ vĩ và kiến trúc nhà tường trình dày cộp. Thời tiết cực Tây khắc nghiệt gây thiếu nước và ảnh hưởng sinh kế.",
  "pa-then": "Bí ẩn với lễ hội Nhảy Lửa thiêng liêng khiến du khách ngỡ ngàng. Tuy nhiên kinh tế tự túc là chính, hệ thống y tế chăm sóc sức khỏe còn nhiều khoảng trống.",
  "chu-ru": "Tài hoa với nghề làm gốm không dùng bàn xoay và làm nhẫn bạc. Cần thêm nguồn lực thương mại để đưa sản phẩm đi xa, cải thiện đời sống.",
  lao: "Đời sống tương đối ổn định ven các thung lũng Điện Biên, Sơn La. Cần lưu giữ tốt hơn các điệu Lăm Vông và lễ hội Té nước đang ít được tổ chức.",
  giay: "Kinh tế thung lũng lúa nước khá ổn định, người dân giỏi làm lạp xưởng và bánh khảo. Lễ hội Roóng Poọc đang cần được rót vốn để duy trì tổ chức hàng năm.",
  "gie-trieng": "Giữ được tục cõng củi cưới chồng rất độc đáo. Sống ở vùng cao biên giới giáp Nam Lào, việc tiếp cận y tế hiện đại và học chữ còn rất nhiều cản trở.",
  "ta-oi": "Nổi tiếng khắp vùng với nghệ thuật dệt Zèng tinh xảo. Địa hình Trường Sơn hiểm trở cản trở giao thương, đời sống cái mặc có đủ nhưng cái ăn vẫn vất vả.",
  ma: "Từng có truyền thống dệt thổ cẩm rực rỡ bên dòng Đạ Đờng. Đang rất cần được hỗ trợ để mở rộng quy mô kinh tế địa phương và trường học.",
  co: "Xưa nay đều là những bậc thầy trồng quế ở núi Trà Bồng. Đường núi dốc cheo leo khiến y tế dự phòng chưa được tiếp cận đầy đủ khi ốm đau.",
  "cho-ro": "Kinh tế đã hội nhập khá tốt ở vùng đất đỏ Đồng Nai. Tuy nhiên, không gian rừng suy giảm khiến các nghi lễ cúng thần lúa (Yang Va) vắng bóng hoàn toàn.",
  "xinh-mun": "Quần cư ở dọc biên giới Việt - Lào. Trẻ em gặp vô vàn khó khăn khi qua suối đến lớp, kinh tế chủ yếu tự cung tự cấp dựa vào hái lượm.",
  "bru-van-kieu": "Vượt qua bom đạn chiến tranh, họ sống kiên cường ở Tây Quảng Trị. Giao thông khó khăn, đói nghèo còn tiếp diễn, trường lớp đơn sơ là nỗi lo lớn nhất.",
  "co-tu": "Nhà Gươl và điệu múa Tung tung da dá là báu vật sống. Tuy nhiên, đường vào bản hay sạt lở mùa mưa, thương lái không vào được khiến nông sản ứ đọng.",
  ngai: "Số lượng ít, sống đan xen ở đồng bằng và thạo nghề biển, buôn bán. Đời sống vật chất rất cao nhưng bản sắc văn hóa đã bị đồng hóa mạnh mẽ.",
  "si-la": "Dân số ít ỏi giáp biên giới Lai Châu. Tỷ lệ hộ nghèo cao, bà con cần hỗ trợ lương thực khẩn cấp, việc bảo tồn văn hóa gặp khó vì mải lo sinh kế.",
  "pu-peo": "Một trong những dân tộc ít người nhất Hà Giang. Đất đai khô cằn, kinh tế tụt hậu, việc giữ gìn tiếng nói riêng đang là cuộc chiến vô cùng gian nan.",
  "ro-mam": "Chỉ còn một làng duy nhất ở biên giới Kon Tum. Nhờ nhà nước, điện đường đã có, kinh tế khá lên nhưng thanh niên không còn ai biết nghề truyền thống.",
  cong: "Làng bản mờ sương ở Điện Biên, sống hòa thuận với tự nhiên. Nguy cơ dịch bệnh cao do khoảng cách quá xa trạm xá, đời sống kinh tế tự túc 100%.",
  "bo-y": "Có nghề làm thợ mộc và rèn đúc rất khéo léo. Nhìn chung vẫn chật vật về kinh tế do đường sá vận chuyển hàng hóa bị chia cắt bởi đồi núi.",
  khang: "Được mệnh danh là những chú rái cá giỏi làm thuyền độc mộc Tây Bắc. Sinh kế sông nước bấp bênh, bản làng thiếu trạm y tế chuẩn phòng khi mưa lũ.",
  mang: "Cư trú ven những con sông nậm Tây Bắc. Rất khó khăn, tỷ lệ đói nghèo còn cao, tiếng nói và văn hóa cổ bị lai tạp mạnh do nghèo đói chi phối.",
  "co-lao": "Bám rễ trên cao nguyên đá Hoàng Su Phì. Thiếu nước trầm trọng vào mùa khô ảnh hưởng cả kinh tế nương rẫy lẫn vệ sinh sức khỏe cộng đồng.",
  lu: "Người phụ nữ Lự nhuộm răng đen và dệt vải cực đỉnh. Mức sống trung bình thấp do xa trung tâm, cần hỗ trợ thêm thuốc men phòng dịch bệnh.",
  "lo-lo": "Dù ít người nhưng sở hữu điệu múa trống đồng cổ xưa rực rỡ nhất Hà Giang. Khí hậu đá tai mèo khắc nghiệt cản trở kinh tế, y tế vô cùng thiếu thốn.",
  "o-du": "Dân tộc ít người nhất Việt Nam ở Nghệ An. Nhà cửa và y tế được bao cấp khá ổn định, nhưng số người biết nói tiếng Ơ Đu đếm chưa qua hết ngón tay.",
  mnong: "Lưu giữ kho tàng sử thi Ot N'drong khổng lồ. Việc thuần dưỡng voi mang lại bản sắc lớn nhưng kinh tế hộ gia đình vẫn eo hẹp, cần nâng cấp trạm y tế.",
  xtieng: "Sống quanh vùng Bình Phước, kinh tế mủ cao su giúp đời sống đi lên. Việc bảo tồn nghệ thuật cồng chiêng và lễ hội đâm trâu trong giới trẻ đang là thách thức.",
  ruck: "Không có dữ liệu hint cụ thể khả dụng"
};

console.log("Hints data compiled. Ready for insertion into ethnic groups data.");
